version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 0
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    assignees:
      - lorrandalx
  - package-ecosystem: "docker"
    directory: "/"
    open-pull-requests-limit: 0
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    assignees:
      - lorrandalx
  - package-ecosystem: "gomod"
    directory: "/"
    open-pull-requests-limit: 0
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    assignees:
      - lorrandalx
